import './app.js';
import { loadData } from './data-loader.js';

const elements = { levelFilter: document.querySelector('[data-level-filter]'), domainFilter: document.querySelector('[data-domain-filter]'), count: document.querySelector('[data-question-count]'), score: document.querySelector('[data-score]'), loading: document.querySelector('[data-quiz-loading]'), content: document.querySelector('[data-question-content]'), empty: document.querySelector('[data-empty]'), error: document.querySelector('[data-error]'), id: document.querySelector('[data-question-id]'), type: document.querySelector('[data-question-type]'), question: document.querySelector('[data-question]'), options: document.querySelector('[data-options]'), submit: document.querySelector('[data-submit]'), next: document.querySelector('[data-next]'), feedback: document.querySelector('[data-feedback]'), reviewStatus: document.querySelector('[data-review-status]'), relatedDomain: document.querySelector('[data-related-domain]'), relatedGlossary: document.querySelector('[data-related-glossary]'), relatedWorkflow: document.querySelector('[data-related-workflow]') };
const levelLabels = { Concept: 'Level 1 Concept', Logic: 'Level 2 Logic', Troubleshooting: 'Level 3 Troubleshooting', 'Engineering Decision': 'Level 4 Engineering Decision' };
const relatedGlossary = { Material: 'Thermal Conductivity, Thermal Resistance', Radiation: 'Emissivity', Flow: 'Flow Rate, Pressure Drop', Fan: 'P-Q Curve, Operating Point', Thermal: 'Thermal Resistance', 'Thermal Design': 'Thermal Resistance', 'Heat Sink': 'Fin Pitch', Power: 'Thermal Resistance', Mesh: 'Mesh, Convergence' };
const relatedWorkflow = { Material: 'Material', Radiation: 'Thermal', Flow: 'Flow', Fan: 'Flow', Thermal: 'Thermal', 'Thermal Design': 'Thermal', 'Heat Sink': 'Thermal', Power: 'Power', Mesh: 'Mesh' };
const state = { questions: [], filtered: [], currentIndex: 0, selected: null, submitted: false, score: 0, answered: 0, level: 'all', domain: 'all' };

function answerIndex(question) { if (typeof question.answerIndex === 'number') return question.answerIndex; if (typeof question.answer === 'number') return question.answer; const answer = String(question.answer || '').trim().toUpperCase(); return answer.length === 1 ? answer.charCodeAt(0) - 65 : question.options?.findIndex((option) => option === question.answer); }
function resetQuestion() { state.selected = null; state.submitted = false; }
function renderFilters() {
  elements.levelFilter.innerHTML = ['all', ...Object.keys(levelLabels)].map((level) => `<button class="level-button ${state.level === level ? 'is-active' : ''}" type="button" data-level="${level}">${level === 'all' ? 'All Levels' : levelLabels[level]}</button>`).join('');
  elements.domainFilter.innerHTML = '<option value="all">All domains</option>' + [...new Set(state.questions.map((question) => question.domain).filter(Boolean))].sort().map((domain) => `<option value="${domain}">${domain}</option>`).join(''); elements.domainFilter.value = state.domain;
  elements.levelFilter.querySelectorAll('[data-level]').forEach((button) => button.addEventListener('click', () => { state.level = button.dataset.level; state.currentIndex = 0; resetQuestion(); renderFilters(); applyFilters(); }));
  elements.domainFilter.onchange = () => { state.domain = elements.domainFilter.value; state.currentIndex = 0; resetQuestion(); applyFilters(); };
}
function applyFilters() { state.filtered = state.questions.filter((question) => (state.level === 'all' || question.level === state.level) && (state.domain === 'all' || question.domain === state.domain)); state.currentIndex = Math.min(state.currentIndex, Math.max(0, state.filtered.length - 1)); renderQuestion(); }
function renderQuestion() {
  const question = state.filtered[state.currentIndex]; elements.count.textContent = question ? `${state.currentIndex + 1} / ${state.filtered.length}` : `0 / ${state.filtered.length}`; elements.score.textContent = `${state.score} / ${state.answered}`; elements.empty.hidden = Boolean(question); elements.content.hidden = !question; if (!question) return;
  elements.id.textContent = `${question.id} · ${question.level.toUpperCase()}`; elements.type.textContent = question.type || 'Question'; elements.question.textContent = question.question; elements.options.innerHTML = (question.options || []).map((option, index) => `<button type="button" data-option="${index}" role="radio" aria-checked="false"><span class="option-key">${String.fromCharCode(65 + index)}</span><span>${option}</span></button>`).join(''); elements.feedback.textContent = ''; elements.feedback.className = 'quiz-feedback'; elements.submit.disabled = true; elements.next.disabled = true; elements.reviewStatus.textContent = 'Submit an answer to review this question.'; elements.relatedDomain.textContent = question.domain || '—'; elements.relatedGlossary.textContent = relatedGlossary[question.domain] || 'See Glossary'; elements.relatedWorkflow.textContent = relatedWorkflow[question.domain] || (question.level === 'Troubleshooting' ? 'Solver' : '—');
  elements.options.querySelectorAll('[data-option]').forEach((button) => button.addEventListener('click', () => { if (state.submitted) return; state.selected = Number(button.dataset.option); elements.options.querySelectorAll('[data-option]').forEach((item) => { item.classList.toggle('is-selected', item === button); item.setAttribute('aria-checked', item === button ? 'true' : 'false'); }); elements.submit.disabled = false; }));
}
function submitAnswer() { const question = state.filtered[state.currentIndex]; if (!question || state.selected === null || state.submitted) return; state.submitted = true; const correct = state.selected === answerIndex(question); state.answered += 1; if (correct) state.score += 1; elements.options.querySelectorAll('[data-option]').forEach((button) => { const index = Number(button.dataset.option); button.disabled = true; button.classList.toggle('is-correct', index === answerIndex(question)); button.classList.toggle('is-wrong', index === state.selected && !correct); }); elements.feedback.textContent = `${correct ? 'Correct' : 'Incorrect'} · Correct Answer: ${question.answer}. ${question.explanation}`; elements.feedback.classList.add(correct ? 'is-correct' : 'is-wrong'); elements.reviewStatus.textContent = correct ? 'Correct answer. Review the explanation and related knowledge.' : 'Incorrect answer. Review the correct answer and explanation.'; elements.submit.disabled = true; elements.next.disabled = false; elements.score.textContent = `${state.score} / ${state.answered}`; }
elements.submit.addEventListener('click', submitAnswer); elements.next.addEventListener('click', () => { if (!state.submitted || !state.filtered.length) return; state.currentIndex = (state.currentIndex + 1) % state.filtered.length; resetQuestion(); renderQuestion(); });
loadData('quiz').then((data) => { state.questions = data.questions || []; renderFilters(); applyFilters(); elements.loading.hidden = true; }).catch((error) => { elements.loading.hidden = true; elements.error.hidden = false; elements.error.textContent = `Quiz could not load: ${error.message}`; });
